FROM maven:3.9.3-eclipse-temurin-17 AS build
RUN mkdir -p /opt/app
COPY ./SWZ_Client-Server-Programm/ /opt/app/
WORKDIR /opt/app/
RUN mvn install

FROM eclipse-temurin:17-jdk
RUN mkdir /opt/app
COPY --from=build /opt/app/Server/target/Server-2.0.jar /opt/app
COPY --from=build /opt/app/Server/target/libs /opt/app/libs
WORKDIR /opt/app
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "Server-2.0.jar"]