INSERT INTO subfields
VALUES (0x1, 'Artificial intelligence'),
       (0x2, 'Programming languages and logic'),
       (0x3, 'Scientific computing applications'),
       (0x4, 'Theory of computation'),
       (0x5, 'Data structures and algorithms'),
       (0x6, 'Computer architecture and organization'),
       (0x7, 'Computer networks'),
       (0x8, 'Computer security in cryptography'),
       (0x9, 'Databases and data mining'),
       (0xA, 'Computer graphics and visualization'),
       (0xB, 'Image and sound processing'),
       (0xC, 'Concurrent, parallel and distributed computing'),
       (0xD, 'Human-computer interaction'),
       (0xE, 'Software engineering'),
       (0xF, 'Information and coding theory');